import Head from '@/components/head';
import './globals.css';

export const metadata = {
  title: 'Детективное агентство "Право"',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ru'>
      <body className='font-sans antialiased'>
        <div className='container mx-auto'>
          <Head />
          <main className='flex min-h-screen flex-col items-center justify-between p-24'>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
