import Footer from '@/components/footer';
import Head from '@/components/head';
import './globals.css';

export const metadata = {
  title: 'Детективное агентство "Право"',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ru'>
      <body className='font-sans antialiased selection:bg-red-600 selection:text-black'>
        <div className='container mx-auto'>
          <Head />
          <main className='flex flex-col items-center justify-between'>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
